INPUT_FPS = 12  # When set to None the fps will be inferred using opencv.

FRAME_SAMPLE_INTERVAL = 5
HASH_LIST_WINDOW_SIZE_IN_SECONDS = 60
LOOP_CHECK_INTERVAL_IN_SECONDS = 5

IMAGE_HASH_SIZE = 12

LOOP_MIN_OCCURRENCES = 5
LOOP_MIN_DURATION_IN_SECONDS = 3
LOOP_DIFF_MARGIN_ERROR = 3
